apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingapp
  namespace: dev
  labels:
    app: bankingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankingapp
  template:
    metadata:
      labels:
        app: bankingapp
    spec:
      containers:
      - name: bankingapp
        image: harihdp/bankingproject:2   # Jenkins will replace `:2` with ${BUILD_NUMBER}
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankingapp
  namespace: dev
  labels:
    app: bankingapp
spec:
  selector:
    app: bankingapp
  type: NodePort
  ports:
  - nodePort: 30080   # <-- must be 30000–32767
    port: 8082
    targetPort: 8082
